### ISSUE TITLE
Uninstall with ansible

### ISSUE THREAD

**Issue by moan0s** [moan0s/matrix-registration-bot#10]
The ansible roles could also provide a uninstall role that is triggered by` matrix-registration-bot-enabled=false`.
In the `main.yml` it would look like this:
```
- import_tasks: "{{ role_path }}/tasks/setup_uninstall.yml"
  when: "run_setup|bool and not matrix_registration_bot_enabled|bool"
  tags:
    - setup-all
    - setup-matrix-registration-bot
```
