### ISSUE TITLE
Check if service is still healthy

### ISSUE THREAD

**Issue by Babalion** [moan0s/matrix-registration-bot#25]
I suggest adding a health check to the `docker-compose.yml` file.
I can create a pull request for this, but I am unsure which would be the best way to check if the service is still healthy.

I am grateful for any help!

**Comment by Babalion** [comment]
Of course!

In a common matrix-synapse `docker-compose.yml` one can add the following healthcheck:
``` yaml
healthcheck:
  test: ["CMD", "curl", "-fSs", "http://localhost:8008/health"]
  interval: 15s
  timeout: 5s
  retries: 3
  start_period: 5s
```

The command specified after `test` will be executed by the docker-daemon in the given interval.
After specified retries or timeor the docker-daemon will mark the service as unhealthy.
It is now up to the server-administrator how to proceed with unhealthy services (for example send a notification, restart the container etc.).

So the question is, what command could be executed regularly in the bot container that succeeds when everything is fine and fails when something has gone wrong?
